sudo: false
dist: jessie
language: java
jdk:
  # Install JDK8 for html5 validator.
  - oraclejdk8
env:
  - NODE_VERSION="6.11.2" PHANTOMJS_VERSION="2.1.1" PATH="$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
cache:
  directories:
    - travis_phantomjs
before_install: |
  nvm install $NODE_VERSION
  # Make sure cached PhantomJS is up to date
  if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then
    rm -rf $PWD/travis_phantomjs
    mkdir -p $PWD/travis_phantomjs
    wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 \
      -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2
    tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 \
      -C $PWD/travis_phantomjs
  fi
  phantomjs --version
install:
  # Disable the spinner; it looks bad on Travis.
  - npm config set spin false
  - npm install
  - pip install --user html5validator
script: |
  ./build
deploy:
  provider: firebase
  token:
    secure: "sW8jrLD4FxUSVEPdCr2l2IWXNvL4rRyJdX1UvNF+lUqcWrerQPDJaVNXBMVWxtU5fKB9+2b7Gl4jnC4OjEtt8NkJeeBLh6+YZy/JW+mMkiFJVWWzx3DuJNJtBnoDJsyovADahVbZRxZPY4wGPsnmfY56wHmB061wy/h48ws1pE9jelZW0vzgqyabw3SNT+mK40wbJSHL1R3ik6DFON67ubuclOMdIw19q/Dyx1ItjioXYXJgC11F2c6Y2pU3sFBU/6xzLF/xevPS146hGriaDBuERl0OP6RfPMZx2N9ZVyVGIuiNicknEWM0WsHe7Ia53il7YbTnJXu+my4k1XFlN/0DxTlZkLb2dhh2n3dEHmUhcW0KxjOjx3ypcx0CevsJJgJ1EfZglHPr+MUM++SST0PkHStD0kbzv/ReKdbLFJRDeZirtM6txmx7aIrTf8av7jSHfItJ0C/9vK8+Xiea4uucSS8QDmR6qtq6xWkx2D1XT7mqjIZHcP0CIujMMb6H6Ga46FCFVMK7ycImjr3JkpBie8AwBr49upjhBnyaSiZvu9TZCJsOU4X1mmAfWC6BnXhllQcDXX/uJAsz173C0Mgvng+5NaYiG7YuxWX3Tj5aS6mVifqiFRzfZyflAP40js8tjKmuiFvdXw21nTdYktLilwgw3gqO5SAP3e6iQBc="
  skip_cleanup: true
